MvcProjectKampi/Controllers/AdminCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.FluentValidation.ValidationRules;
using DataAccessLayer.Concrete.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace MvcProjectKampi.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager _categoryManager = new CategoryManager(new EfCategoryDal());

        // GET: AdminCategory
        public ActionResult Index()
        {
            var categoryValues = _categoryManager.GetList();
            return View(categoryValues);
        }

        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Category category)
        {
            CategoryValidation categoryValidation = new CategoryValidation();
            ValidationResult results = categoryValidation.Validate(category);
            if (results.IsValid)
            {
                _categoryManager.Add(category);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var errorItem in results.Errors)
                {
                    ModelState.AddModelError(errorItem.PropertyName, errorItem.ErrorMessage);
                }
            }
            return View();
        }
    }
}

MvcProjectKampi/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.FluentValidation.ValidationRules;
using DataAccessLayer.Concrete.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace MvcProjectKampi.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager _categoryManager = new CategoryManager(new EfCategoryDal());

        public ActionResult Index()
        {
            var categoryValues = _categoryManager.GetList();
            return View(categoryValues);
        }
        
        public ActionResult GetCategoryList()
        {
            var categoryValues = _categoryManager.GetList();
            return View(categoryValues);
        }

        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Category category)
        {
            CategoryValidation categoryValidation = new CategoryValidation();
            ValidationResult results = categoryValidation.Validate(category);
            if (results.IsValid)
            {
                _categoryManager.Add(category);
                return RedirectToAction("GetCategoryList");
            }
            else
            {
                foreach (var errorItem in results.Errors)
                {
                    ModelState.AddModelError(errorItem.PropertyName,errorItem.ErrorMessage);
                }
            }
            return View();
        }
    }
}

MvcProjectKampi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectKampi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MvcProjectKampi/Views/AdminCategory/Add.cshtml
@using EntityLayer.Concrete
@model Category
@{
    ViewBag.Title = "Kategori Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Quick Example</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                @using (Html.BeginForm("Add", "AdminCategory", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <div class="card-body">
                        <div class="form-group">
                            @Html.LabelFor(m => m.Name, null, new { @class = "col-sm-2" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(m => m.Name, null, new { @class = "form-control", @placeholder = "Kategori Adı Giriniz" })
                                @Html.ValidationMessageFor(m => m.Name, null, new { @class = "help-block text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Description, null, new { @class = "col-sm-2" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(m => m.Description, null, new { @class = "form-control", @placeholder = "Katgori Açıklaması Giriniz" })
                                @Html.ValidationMessageFor(m => m.Description, null, new { @class = "help-block text-danger" })
                            </div>
                        </div>
                        <div class="form-check">
                            @Html.CheckBoxFor(model => model.isActive,new { @class = "form-check-input" })
                            <label class="form-check-label" for="isActive">Aktif Mi</label>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Ekle</button>
                    </div>
                }
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

MvcProjectKampi/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "Kategoriler";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section styles {
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Content/_adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Content/_adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">DataTable with default features</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Başlık</th>
                            <th>Açıklama</th>
                            <th>Durum</th>
                            <th>-</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var categoryItem in Model)
                        {
                            <tr>
                                <th scope="row">@categoryItem.Id</th>
                                <td>@categoryItem.Name</td>
                                <td>@categoryItem.Description</td>
                                <td>@categoryItem.isActive</td>
                                <td>
                                    <a href="/@categoryItem.Id" class="btn btn-info">Başlıklar</a> &nbsp; 
                                    <a href="/@categoryItem.Id" class="btn btn-primary">Düzenle</a> &nbsp; 
                                    <a href="/@categoryItem.Id" class="btn btn-warning">Sil</a>
                                </td>
                            </tr>
                        }
                        </tbody>
                        
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</div>
<!-- /.container-fluid -->
@section scripts{
    <!-- DataTables  & Plugins -->
    <script src="~/Content/_adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/_adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/_adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/_adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script type="text/javascript">
    $(function () {
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
            })
        });
        </script>
}

MvcProjectKampi/Views/Category/Add.cshtml
@using EntityLayer.Concrete
@model Category
@{
    ViewBag.Title = "Add";
}

@using (Html.BeginForm("Add", "Category", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Name, null, new { @class = "col-sm-2" })
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Name, null, new { @class = "form-control", @placeholder = "Kategori Adı Giriniz" })
            @Html.ValidationMessageFor(m => m.Name, null, new { @class = "help-block text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description, null, new { @class = "col-sm-2" })
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Description, null, new { @class = "form-control", @placeholder = "Katgori Açıklaması Giriniz" })
            @Html.ValidationMessageFor(m => m.Description,null,new { @class = "help-block text-danger" })
        </div>
    </div>
    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(model => model.isActive) Aktfif Mi
        </label>
    </div>
    <br/>
    <button type="submit" class="btn btn-default">Submit</button>
}

MvcProjectKampi/Views/Category/GetCategoryList.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "GetCategoryList";
}

@if (@Model.Count > 0)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">No</th>
                <th scope="col">Başlık</th>
                <th scope="col">Açıklama</th>
                <th scope="col">Durum</th>
                <th scope="col">-</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var categoryItem in Model)
            {
                <tr>
                    <th scope="row">@categoryItem.Id</th>
                    <td>@categoryItem.Name</td>
                    <td>@categoryItem.Description</td>
                    <td>@categoryItem.isActive</td>
                    <td><a href="/@categoryItem.Id" class="btn btn-primary">Düzenle</a> &nbsp; <a href="/@categoryItem.Id" class="btn btn-warning">Sil</a></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info">
        <p>Henüz bir kategori eklenmemiştir.</p>
    </div>
}

MvcProjectKampi/Views/Category/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "Kategori Listesi";
}
@Html.ActionLink("Kategori Ekle","Add","Category", null, new { @class= "btn btn-primary" })
@Html.ActionLink("Kategori Listesi","GetCategoryList","Category", null, new { @class="btn btn-warning"})
<br /><br />
@if (@Model.Count > 0)
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">No</th>
                <th scope="col">Başlık</th>
                <th scope="col">Açıklama</th>
                <th scope="col">Durum</th>
                <th scope="col">-</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var categoryItem in Model)
            {
                <tr>
                    <th scope="row">@categoryItem.Id</th>
                    <td>@categoryItem.Name</td>
                    <td>@categoryItem.Description</td>
                    <td>@categoryItem.isActive</td>
                    <td><a href="/@categoryItem.Id" class="btn btn-primary">Düzenle</a> &nbsp; <a href="/@categoryItem.Id" class="btn btn-warning">Sil</a></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info">
        <p>Henüz bir kategori eklenmemiştir.</p>
    </div>
}

MvcProjectKampi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Anasayfa";
}

<div class="jumbotron" style="margin-top:20px;">
    <h1>MVC Kampı</h1>
    <p class="lead">Eğitmen : Murat Yücedağ</p>
    <p class="lead">Kurs Tarihi : 09/04/2021</p>
</div>

MvcProjectKampi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mvc Kampı</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mvc Kampı", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Anasayfa", "Index", "Home")</li>
                    <li>@Html.ActionLink("Kategoriler", "Index", "Category")</li>
                </ul>
            </div>
        </div>
    </div>
<div class="container body-content">
    <br/>
    @RenderBody()


</div>
    <footer style="position: fixed; height: 70px; bottom: 0; width: 100%; text-align:center;">
        <hr />
        <p>&copy; @DateTime.Now.Year - Mvc Kampı</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>